#-----------------------
# GLOBAL CONFIGURATIONS
#-----------------------
global:
  strimzi-kafka-operator:
    enabled: true
  kafka-cluster:
    enabled: true
  kafka-connect-cluster:
    enabled: true
  kafka-ui-redpanda-console:
    enabled: true

##-------------------------
## COMPONENT CONFIGURATIONS
##-------------------------
strimzi-kafka-operator:
  kafkaConnect:
    image:
      registry: ""
#      name: ""
      tagPrefix: ""

kafka-ui-redpanda-console:
  console:
    console:
      config:
        kafka:
          brokers:
            - my-cluster-kafka-brokers:9092
        connect:
          enabled: true
          clusters:
            - name: "kafka-connect-cluster"
              url: "http://my-connect-cluster-connect-api:8083"
